WIP: Add quickstart devs
cvmfs/doc-cvmfs pull request #188
Opened 2022-09-01 13:54 UTC by HereThereBeDragons

Related https://github.com/cvmfs/cvmfs/issues/3044

Please give feedback

Todos:
- Add references to the different topics within the documentation
- Unify/Streamline layout (e.g. what type of header is used where)

2022-09-01 20:21 UTC, jblomer commented on devs-cpt-git.rst
> +JIRA Ticket ``CVM-<Number>``
Perhaps we can extend that for github, like `gh-<Number>`

2022-09-01 20:24 UTC, jblomer commented
That's pretty cool!  I think we should put this documentation as markdown in the main sources under `/doc`.  But we should merge here your fixes to the quickstart guide and the authors list.

2022-09-01 21:10 UTC, HereThereBeDragons commented
ok, should be no problem to create this also as markdowns. the original doc was done in markdown anyway.

btw one more thing i forgot: the file structure
i have now put every section in a different file - which means the entire chapter cannot be viewed as continuous scrolling experience.
if we want this, i have to reconsider how to solve it. for editing the separate files are definitely better.

2022-10-04 19:50 UTC, jblomer requested changes
Many thanks! Almost ready to be merged.

2022-10-04 19:50 UTC, jblomer commented on _static/css/custom.css
> +}
Missing newline at the end of the file

2022-10-04 19:50 UTC, jblomer commented on cpt-configure.rst
> +``cvmfs_config showconfig`` or ``cvmfs_config stat``. Four commands might
```suggestion
``cvmfs_config showconfig`` or ``cvmfs_config stat``. The following commands might
```

2023-01-20 13:37 UTC, HereThereBeDragons commented
Close, because it is now in cvmfs main repo

2023-01-20 13:37 UTC, closed without merging